my_list = [10, 20, 30, 40, 50]
print("Initial list:", my_list)
my_list.append(60)
print("List after appending 60:", my_list)
my_list.remove(30)
print("List after removing 30:", my_list)
my_list.insert(2, 35)
print("List after inserting 35 at index 2:", my_list)
print("Element at index 3:", my_list[3])
print("Sliced list:", my_list[1:4])
print("Length of the list:", len(my_list))
my_list.sort()
print("Sorted list:", my_list)
my_list.reverse()
print("Reversed list:", my_list)
